### ISSUE TITLE
NL Drenthe

### ISSUE THREAD

**Issue by julianbernauer** [julianbernauer/polidoc#224]
Offen: 
"Volkspartij voor Vrijheid- diese Partei heißt Partij voor Vrijheid:
Wurde vermutlich mit der Volkspartij voor Vrijheid en democracj verwechselt!
Beide Parteien wurden aber richtig Codiert"

**Comment by AnnaWohl** [comment]
Diesen Fehler habe ich soweit ich weiß später selbst bemerkt und bereits korrigiert, kann das sein? Ich sehe bei Drenthe zumindest nur noch Partij voor Vrijheid.
