### ISSUE TITLE
Bayern 

### ISSUE THREAD

**Issue by julianbernauer** [julianbernauer/polidoc#232]
Offen: 
Codierung der Grünen noch einmal überprüfen, da manchmal 41111 oder 41113 genutzt wird (auch keine klare Differenzierung zwischen Die Grünen und Bündnis90/Die Grünen)

Außerdem Parteiprogramm der SPD muss in 2013 auf polidoc noch in "Jetzt ist alles drin! Wir bringen Bayern ins Gleichgewicht." umgewandelt werden

**Comment by AnnaWohl** [comment]
Änderung Titel 2013 SPD ist erledigt
