### ISSUE TITLE
Wahlprogramme von Prof. Pappi hinzufügen 

### ISSUE THREAD

**Issue by julianbernauer** [julianbernauer/polidoc#245]

**Comment by julianbernauer** [comment]
Die Dateien habe ich, es sind etwa 160 Dokumente

**Comment by julianbernauer** [comment]
Memo: Doku aktualisieren

**Comment by AnnaWohl** [comment]
Ich habe die Programme jetzt alle nochmal überprüft, wir haben sie alle schon hochgeladen. die neuen sind aber um einiges leserlicher bearbeitet. Wie sollen wir verfahren? Zwei Programme unter dem gleichen Namen hochladen geht so wie ich das gesehen habe nicht.
