### ISSUE TITLE
Fehlermeldung beim Löschen von Dateien

### ISSUE THREAD

**Issue by AnnaWohl** [julianbernauer/polidoc#272]
Durch die Änderungen bei den alten Wahlprogrammen müssen einige gelöscht werden hier kommt die Fehlermeldung:
Deleting 41521.003.1988.1.2 failed. You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''41521.003.1988.1.2'' at line 1
Jetzt hat es geklappt - das Problem ist jetzt aber schon häufiger aufgetreten. Falls es nochmal auftritt sollte man vielleicht mal bei der IT fragen ob sie da einen möglichen Grund sehen.

**Comment by AnnaWohl** [comment]
Daten eingeben funktioniert nicht:
NRW grüne 1980
Hamburg 1986 Grüne
Bremen/Hamburg Grüne 87
BW Grüne 88

**Comment by julianbernauer** [comment]
Ich schaue es mir an

**Comment by julianbernauer** [comment]
Sollte sich erledigt haben?!
