### ISSUE TITLE
Österreich Zug

### ISSUE THREAD

**Issue by AnnaWohl** [julianbernauer/polidoc#278]
wir haben Zug als Region gelistet, darin befinden sich keine Programme.
Soweit ich weiß gehört das nicht auf die Landtage Ebene oder?

**Comment by julianbernauer** [comment]
Vielleicht ein Verknüpfungsfehler, Zug gehört als Kanton zur Schweiz

**Comment by julianbernauer** [comment]
Ich habe die Kategorie gelöscht. 
Beunruhigende Rückmeldung: "91 deleted successfully". Ich sehe aber bisher keine verlorenen Einträge.

**Comment by julianbernauer** [comment]
Ebenso "Spain Kronobergs län" gelöscht. "102 deleted successfully!"
