### ISSUE TITLE
Nationalratswahl Österreich 2017

### ISSUE THREAD

**Issue by AnnaWohl** [julianbernauer/polidoc#279]
alle WPs

**Comment by julianbernauer** [comment]
Bei den anderen wahrscheinlich auch...

**Comment by AnnaWohl** [comment]
ÖVP und SPÖ sind noch nicht fertig! Bei den anderen Parteien müsste es passen

**Comment by AnnaWohl** [comment]
alle hochgeladen bis auf ÖVP

**Comment by julianbernauer** [comment]
Das Programm ist aber fertig, wie ich höre?

**Comment by AnnaWohl** [comment]
Ja ÖVP ist fertig - liegt auf repcong

**Comment by AnnaWohl** [comment]
alle Programme 2017 sind hochgeladen
