### ISSUE TITLE
Deutschland Bundestagswahl 2017

### ISSUE THREAD

**Issue by AnnaWohl** [julianbernauer/polidoc#286]

**Comment by LeonardSchmidt** [comment]
Josephine hatte die BTW-Programme 2017 umgewandelt. 
liegen in L:\swnspw3 -> Projekte    und müssen nur noch auf Polidoc hochgeladen werden. 

Zugang zu Ordner "Projekte" ist jedoch für Hiwis gesperrt, spreche das mit Josephine ab.

**Comment by julianbernauer** [comment]
Auf repcong liegen auch Programme, bitte Aktualität prüfen. Ich würde sie hochladen, wenn es die richtigen sind, habe es vorbereitet.
