### ISSUE TITLE
Parlamentswahl Italien März 2018

### ISSUE THREAD

**Issue by AnnaWohl** [julianbernauer/polidoc#287]

**Comment by LeonardSchmidt** [comment]
Codes für Wahlbündnisse unklar, teils komplett neue Parteien/Bündnisse

M5S(Five Star Movement): nicht ein zusammenhängendes Wahlprogramm, sondern ca. 20 einzelne thematische PDFs & unklar ob Wahl- oder Parteiprogramm

**Comment by LeonardSchmidt** [comment]
siehe Kommentar vom 21.03.2018

**Comment by julianbernauer** [comment]
Codes vergeben, Programme hochgeladen. 
Ausnahme: txt für M5S muss noch geprüft und hochgeladen werden
