### ISSUE TITLE
Parlamentswahlen Schweiz 2015

### ISSUE THREAD

**Issue by AnnaWohl** [julianbernauer/polidoc#296]
Schweizerische Volkspartei bereits da

**Comment by julianbernauer** [comment]
SVP 2015 hatte ich hochgeladen, jetzt auch in Doku eingetragen

**Comment by AnnaWohl** [comment]
FPÖ fehlt

**Comment by julianbernauer** [comment]
FDP, oder?

**Comment by AnnaWohl** [comment]
ja genau

**Comment by AnnaWohl** [comment]
auf Server, nicht auf polidco/doku

**Comment by AnnaWohl** [comment]
alles von 2015 hochgeladen

**Comment by AnnaWohl** [comment]
für die PdAS fehlt der Code - noch nicht hochgeladen

**Comment by julianbernauer** [comment]
PdAS = 43220
