### ISSUE TITLE
Austria national level

### ISSUE THREAD

**Issue by julianbernauer** [julianbernauer/polidoc#3]
- Needs control for coverage 
- Some party names are missing
- cmp code for COAL -> 42001?  
- Clean names of manifestos

**Comment by julianbernauer** [comment]
By the way, 42001 is indeed not known by polidoc.net and needs to be defined there

**Comment by julianbernauer** [comment]
Offen, Punkte von Theresa: 
- Bei dem Wahlprogramm der Grünen Alternative in 1999 ist noch ein falscher Titel auf polidoc.net
- Bei dem Wahlprogramm der SPÖ in 2008 muss noch der Titel auf polidoc.net ergänzt werden

**Comment by AnnaWohl** [comment]
Hier scheint ihr ja doch schon etwas getan zu haben.
Liste Fritz Dinkhauser 2008 Titel auf polidoc ergänzen
ÖVP 1986 ist auf Polidoc nur der erste Teil des Titels
2013 ist das Programm der Österreichischen Bundesregierung dabei??
2008 die Bürgerliste Martin hat keinen Englischen Titel und verschiedene Namen: Grund ist Gründung zu Europawahl - Frage welchen wir benutzen

**Comment by AnnaWohl** [comment]
Grüne 1999 Programmname geändert
SPÖ, Liste Dinkhauser Titel ergänzt

**Comment by julianbernauer** [comment]
- 42001 ist wohl auf polidoc definiert, noch ein Name dazu vergeben: "Regierung" 
- Titel ÖVP 86 ergänzt
- Titel Liste Martin ergänzt
