### ISSUE TITLE
WP Spanien

### ISSUE THREAD

**Issue by AnnaWohl** [julianbernauer/polidoc#303]
liegen bei Hiwi < Antonia < Martin < Cohesify
sowohl pdf als auch txt
mit hochgeladenen abgleichen, hochladen

**Comment by AnnaWohl** [comment]
Antonia kümmert sich darum

**Comment by julianbernauer** [comment]
Programme unter Countries>Spain>2015

**Comment by AntoniaLang** [comment]
Programme 2016 unter Countries>Spain>2016
noch nicht hochgeladen
