### ISSUE TITLE
Griechenland

### ISSUE THREAD

**Issue by julianbernauer** [julianbernauer/polidoc#320]

**Comment by julianbernauer** [comment]
Bei COHESIFY wurden 33 Programme analysiert

**Comment by julianbernauer** [comment]
Ordner Greekmanifestos_per_party

**Comment by julianbernauer** [comment]
Sehe nur 18 .txt, pdf nicht zugeordnet...

**Comment by AnnaWohl** [comment]
erste Programme auf xUpload - bitte hochladen.
Rest kommt, ich muss die meisten aber nochmal überarbeiten.

**Comment by AnnaWohl** [comment]
hier ist jetzt alles klar - die letzten müssen noch hochgeladen werden/ Dokumentation in Upload Übersicht
