### ISSUE TITLE
Speicherorte Programme

### ISSUE THREAD

**Issue by julianbernauer** [julianbernauer/polidoc#322]
- Hier müssen wir einmal einen Überblick bekommen, es scheint nicht alles auf dem repcong-Ordner zu liegen 
- Bitte kommentiert, wo ihr die Programme zum Hochladen ablegt. Habt ihr aufbereitete Programme auf euren Laufwerken? 
- Vor allem gesucht: COHESIFY-Programme aus Zypern, Slovenien, Lombardei, Ungarn, Griechenland, Rumänien

**Comment by julianbernauer** [comment]
Rumänien, Ungarn, Slovenien und Lombardei (im Ungarn-Ordner) sind auf dem repcong-Server

**Comment by AnnaWohl** [comment]
Ich habe ein paar von anderen Hiwis gefunden.
Meine sind alle auf repcong

**Comment by julianbernauer** [comment]
Griechenland und Zypern sind jetzt auch da

**Comment by AntoniaLang** [comment]
Ich habe meine auch immer direkt auf repcong abgelegt
