### ISSUE TITLE
M5S Italia 2018

### ISSUE THREAD

**Issue by julianbernauer** [julianbernauer/polidoc#326]
- 20 pdfs zusammengemergt
- txt für M5S muss noch geprüft und hochgeladen werden -> doc auf repcong

**Comment by david-artukovic** [comment]
- txt für MS5 überarbeitet und auf Repcong hochgeladen

**Comment by julianbernauer** [comment]
Merci!

**Comment by julianbernauer** [comment]
Übernommen, wird hochgeladen
