### ISSUE TITLE
Dänemark 2015

### ISSUE THREAD

**Issue by julianbernauer** [julianbernauer/polidoc#331]
Programme recherchieren und aufbereiten

Social Democrats
Danish People's Party
Venstre 
Red–Green Alliance
Liberal Alliance
The Alternative
Danish Social Liberal Party 
Socialist People's Party 
Conservative People's Party
Christian Democrats

**Comment by julianbernauer** [comment]
Auch eine gute Quelle für Wahlen: http://www.parlgov.org/explore/dnk/election/2015-06-18/

**Comment by julianbernauer** [comment]
Die Programme sind als .txt auf repcong

**Comment by julianbernauer** [comment]
Keine pdfs

**Comment by julianbernauer** [comment]
Bitte teils Text noch nach unseren Regeln aufbereiten (Seitenzahlen...): 
- Countries\Denmark\2015\13401.000.2015.1.1
- 13330.000.2015.1.1
- 13120.000.2015.1.1
- 13720.000.2015.1.1
Rest ist ok

**Comment by salehman96** [comment]
Fertig und auf Repcong 
- 13330.000.2015.1.1 revised
- 13120.000.2015.1.1 revised
- 13720.000.2015.1.1 revised

**Comment by julianbernauer** [comment]
Prima! 
Bitte noch 13401.000.2015.1.1 bereinigen...

**Comment by salehman96** [comment]
Erledigt. Auf Repcong unter: 13401.000.2015.1.1 revised

**Comment by julianbernauer** [comment]
Merci!
