### ISSUE TITLE
UK 2010

### ISSUE THREAD

**Issue by julianbernauer** [julianbernauer/polidoc#332]
UKIP fehlt

**Comment by julianbernauer** [comment]
BNP fehlt

**Comment by julianbernauer** [comment]
Beide auf repcong für die weitere Bearbeitung

**Comment by salehman96** [comment]
BNP Manifesto 2010 umformatiert und bereinigt 
Auf repcong hochgeladen als:
- UK_WP_BNP_2010

**Comment by julianbernauer** [comment]
Danke!
