### ISSUE TITLE
Lombardei

### ISSUE THREAD

**Issue by julianbernauer** [julianbernauer/polidoc#338]
- Bitte Kopien der bereits aufbereiteten Programme (pdf und txt) aus Ordner Countries\Lombardy mit "party_codes" labeln
- Einträge auf polidoc.net 
- In den Ordner "XUpload" 
- Programm PDL national level weglassen

**Comment by LucaJoppien** [comment]
PD 32340.001.2013.1.1

**Comment by salehman96** [comment]
5 Stelle 2013: 32997.001.2013.1.1

**Comment by AnnaWohl** [comment]
Sobald Julian codes hat lade ich es hoch - Dokumentation bei Upload Übersicht
