### ISSUE TITLE
Schweiz/Bern

### ISSUE THREAD

**Issue by julianbernauer** [julianbernauer/polidoc#36]
GPS 1997: "Luzern" im Titel des Programms, Programmtext bezieht sich aber auf Bern -> Titel auf polidoc anpassen
Richtiger Titel: "Leitsätze Grüne - Freie Liste Kanton Bern"

**Comment by julianbernauer** [comment]
Bei der SVP hat es 2002 zwei verschiedene Programme mit dem gleichen Titel

**Comment by theresahenn** [comment]
Habe aus Versehen, das Programm der GPS auf polidoc gelöscht. Werde es wieder hochladen, wenn ich am Rechner im MZES bin. Anscheinend kann man die polidoc Seite doch nicht von Zuhause bearbeiten.

**Comment by AnnaWohl** [comment]
bei der SVP scheint es einfach 2 Versionen des Wahlprogramms mit gleichem titel zu geben

**Comment by julianbernauer** [comment]
GPS 1997 scheint zu fehlen, wieder am MZES-Rechner anlegen und verknüpfen

**Comment by AnnaWohl** [comment]
hat nur auf polidoc gefehlt, erledigt
