### ISSUE TITLE
Schweiz/Thurgau

### ISSUE THREAD

**Issue by julianbernauer** [julianbernauer/polidoc#37]
Manifesto-Titel "Reiseführer"? Checken.

**Comment by AnnaWohl** [comment]
Der Titel lautet eigentlich: Turgau in Bewegung ein politischer Reiseführer.
Ich ändere das hier schon mal- das muss dann aber auch auf Polidoc noch geändert werden

**Comment by AnnaWohl** [comment]
Ansonsten sind in Thurgau noch nicht viele Programme und nur bis 2009

**Comment by AnnaWohl** [comment]
Reiseführertitel ist auch auf Polidoc geändert
