### ISSUE TITLE
Nidwalden

### ISSUE THREAD

**Issue by julianbernauer** [julianbernauer/polidoc#50]

**Comment by AnnaWohl** [comment]
Hier gibt es bei den Grünen einen Eintrag zu 2010 und einen zu 2014. 
Bei 2014 steht allerdings dabei das es sich um Thesen von 2010-2014 handelt.
Ich habe es jetzt mal beibehalten, hier müssen wir erst die Änderung auf polidoc vornehmen!

**Comment by julianbernauer** [comment]
Gute Frage, evtl. wurden das Programm nochmal benutzt, wahrscheinlicher ist, dass es zu 2010 gehört (als zweites Dokument) -> lieber dorthin schieben
@AnnaWohl

**Comment by AnnaWohl** [comment]
erledigt
