### ISSUE TITLE
Zürich

### ISSUE THREAD

**Issue by julianbernauer** [julianbernauer/polidoc#61]

**Comment by AnnaWohl** [comment]
Hier habe ich einige ergänzt die schon online sind.
Ein wichtiger Punkt:
In Polidoc haben wir einen Schreibfehler:
bei 2015 Grüne steht "Grüne ZieleN

**Comment by AnnaWohl** [comment]
seht ihr meinen Kommentar noch, hab es ausversehen geclosed :D

**Comment by julianbernauer** [comment]
Ja, ist wieder da!
