### ISSUE TITLE
Regionen Niederlande

### ISSUE THREAD

**Issue by julianbernauer** [julianbernauer/polidoc#67]
- Noch nicht in der Bestandsliste, .csv anlegen 
- Danach ergänzen

**Comment by julianbernauer** [comment]
Ist angelegt und sollte ergänzt werden

**Comment by AnnaWohl** [comment]
Ich habe Kommentare in pull requests geschrieben, da es vermutlich unübersichtlich wird, wenn wir die alle hier stehen haben

**Comment by AnnaWohl** [comment]
Ist fertig- in manchen Regionen s. pull-requests.
In allen Regionen gab es in 2015 Wahlen, diese sind nicht eingetragen.
Ansonsten sind sehr viele Parteien da!
