### ISSUE TITLE
Sweden national level

### ISSUE THREAD

**Issue by julianbernauer** [julianbernauer/polidoc#98]

**Comment by julianbernauer** [comment]
Theresa: Sverige Democraterna (11710) ist als Partei falsch auf polidoc.net benannt. (ist zusammen geschrieben)

**Comment by julianbernauer** [comment]
Ist es im Original getrennt?

**Comment by AnnaWohl** [comment]
Die Partei schreibt man tatsächlich als ein Wort, muss das dann im file geändert werden?

**Comment by julianbernauer** [comment]
@AnnaWohl in welchem file?

**Comment by AnnaWohl** [comment]
Es stimmt überall.
